ReplicaNumber: 1

probes:
  readiness:
    path: /health/readiness
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
    path: /health/liveliness
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
volume:
  mount:
    path: /tmp/html
containers:
  containerPort: 8080
  image: 'quay.io/slav1970/idbhelloworld'
  tag: 'chart_v2'

service:
  servicePort: 8080